name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: centos-latest

    strategy:
      matrix:
        node-version: [14.15.0]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build --if-present

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 47.118.48.211 
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          local-dir: ./build/
          server-dir: ./htdocs/
        env:
          CI: true
